In [10]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [16]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [17]:
df.shape

(569, 33)

In [18]:
df.drop(columns=['Unnamed: 32' , 'id'] , inplace=True)

In [19]:
df.shape

(569, 31)

In [20]:
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0], test_size=0.2)

In [21]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [22]:
x_train

array([[-0.85208405,  0.70336085, -0.84613619, ..., -0.75851856,
         0.45016877, -0.2006503 ],
       [ 0.20179486, -1.0742328 ,  0.14014115, ...,  0.16746906,
         0.35332701, -0.11533424],
       [ 1.15115684, -0.58712596,  1.09477999, ...,  0.59879674,
        -0.07761885, -0.09441805],
       ...,
       [ 1.20631855, -0.1207962 ,  1.14540159, ...,  0.96481776,
        -0.12603974, -0.10927955],
       [-1.58747669, -0.18312741, -1.58014927, ..., -1.73249898,
         0.40658998, -0.1544145 ],
       [ 1.63019271,  0.52791005,  1.61786977, ...,  1.69230352,
         1.86405856, -0.26339888]])

In [23]:
y_train

,diagnosis
551,B
347,B
444,M
567,M
371,B
...,...
240,B
256,M
317,M
314,B


In [24]:
le=LabelEncoder()
y_train=le.fit_transform(y_train)
y_test=le.transform(y_test)

In [25]:
y_train

array([0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,

In [26]:
x_train=torch.from_numpy(x_train)
x_test=torch.from_numpy(x_test)
y_train=torch.from_numpy(y_train)
y_test=torch.from_numpy(y_test)

In [27]:
x_train

tensor([[-0.8521,  0.7034, -0.8461,  ..., -0.7585,  0.4502, -0.2007],
        [ 0.2018, -1.0742,  0.1401,  ...,  0.1675,  0.3533, -0.1153],
        [ 1.1512, -0.5871,  1.0948,  ...,  0.5988, -0.0776, -0.0944],
        ...,
        [ 1.2063, -0.1208,  1.1454,  ...,  0.9648, -0.1260, -0.1093],
        [-1.5875, -0.1831, -1.5801,  ..., -1.7325,  0.4066, -0.1544],
        [ 1.6302,  0.5279,  1.6179,  ...,  1.6923,  1.8641, -0.2634]],
       dtype=torch.float64)

In [28]:
x_train.shape

torch.Size([455, 30])

In [52]:
class mysimpleneural():

  def __init__(self,X):
    self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)


  def forward(self, X):
    z=torch.matmul(X,self.weights)+self.bias
    y_pred=torch.sigmoid(z)
    return y_pred


  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train * torch.log(y_pred) + (1 - y_train) * torch.log(1 - y_pred)).mean()
    return loss

In [48]:
learning_rate=0.1
epochs=25

In [53]:
model = mysimpleneural(x_train)

for epoch in range(epochs): # Fixed spelling of epoch
    y_pred = model.forward(x_train)

    loss = model.loss_function(y_pred, y_train)
    loss.backward()

    with torch.no_grad():
        # Update parameters
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

        # Correct way to zero gradients manually
        model.weights.grad.zero_()
        model.bias.grad.zero_()

    # Fixed .iten() to .item()
    print(f"Epoch is {epoch+1} and the loss = {loss.item():.4f}")


Epoch is 1 and the loss = 2.8047
Epoch is 2 and the loss = 2.6415
Epoch is 3 and the loss = 2.4691
Epoch is 4 and the loss = 2.2933
Epoch is 5 and the loss = 2.1165
Epoch is 6 and the loss = 1.9431
Epoch is 7 and the loss = 1.7697
Epoch is 8 and the loss = 1.6060
Epoch is 9 and the loss = 1.4539
Epoch is 10 and the loss = 1.3157
Epoch is 11 and the loss = 1.1938
Epoch is 12 and the loss = 1.0901
Epoch is 13 and the loss = 1.0059
Epoch is 14 and the loss = 0.9403
Epoch is 15 and the loss = 0.8912
Epoch is 16 and the loss = 0.8551
Epoch is 17 and the loss = 0.8289
Epoch is 18 and the loss = 0.8094
Epoch is 19 and the loss = 0.7946
Epoch is 20 and the loss = 0.7829
Epoch is 21 and the loss = 0.7734
Epoch is 22 and the loss = 0.7653
Epoch is 23 and the loss = 0.7583
Epoch is 24 and the loss = 0.7521
Epoch is 25 and the loss = 0.7466


In [55]:
model.bias

tensor([-0.2318], dtype=torch.float64, requires_grad=True)

In [57]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(x_test)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.5861803889274597
