In [ ]:
##learning about numpy array and basics

In [2]:
import numpy as np
import time

In [6]:
arr1d = np.array([1,2,3,4,5])
print("the 1d array =",arr1d)

arr2d =np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("the 2d array =",arr2d)

the 1d array = [1 2 3 4 5]
the 2d array = [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [9]:
lis=[4,5,5,4]
print("multiplication by the lis = ",lis*2)

arrnumpy=np.array([4,5,5,4])
print("multiplication by the lis = ",arrnumpy*2)



multiplication by the lis =  [4, 5, 5, 4, 4, 5, 5, 4]
multiplication by the lis =  [ 8 10 10  8]


In [19]:
start = time.time()
pylist =[i*2 for i in range(15200000)]
print("Time = " ,time.time()-start)

start = time.time()
arrnums=np.arange(15200000)*2
print("Time = ",time.time()-start)

Time =  2.4735801219940186
Time =  0.09667515754699707


In [24]:
zeros= np.zeros((3,4))
print("zeros array is \n",zeros)


ones=np.ones((3,4))
print("ones array is \n",ones)

full=np.full((3,4),9)
print("full with 9 =\n",full)

rand=np.random.random((3,4))
print("random matrix = \n",rand*10)


seq=np.arange(0,11,2)
print("sequence =\n",seq)

zeros array is 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array is 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full with 9 =
 [[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]
random matrix = 
 [[0.62183512 5.96059399 9.59472389 2.46081815]
 [2.0631321  3.88229132 3.67078794 7.41623962]
 [6.27959112 0.16633697 9.22875911 4.5454621 ]]
sequence =
 [ 0  2  4  6  8 10]


## vector , matrix, tensor

In [29]:
vector= np.array([1,2,3,4,5])
print("vector\n",vector)

matrix=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("matrix\n",matrix)

tensor=np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
print("tensor\n",tensor)

vector
 [1 2 3 4 5]
matrix
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
tensor
 [[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


## array properties

In [35]:
arrays = np.array([[1,2,5,64],[4,5,7,9]])
print("shape ",arrays.shape)
print("size = ",arrays.size)
print(" Dimension =",arrays.ndim)
print("DataType = ",arrays.dtype)

shape  (2, 4)
size =  8
 Dimension = 2
DataType =  int64


### array Reshaping

In [6]:
newarr=np.arange(12)
print("array is =",newarr)

reshape=newarr.reshape(3,4)
print("reshaped array \n=",reshape)

flaten=reshape.flatten()
print("faten =\n",flaten)

ravel=reshape.ravel()
print("ravel is =\n",ravel)

transpose=reshape.T
print("transpose array =\n",transpose)

array is = [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array 
= [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
faten =
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
ravel is =
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
transpose array =
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
