### numpy array operations

In [1]:
import numpy as np

In [4]:
arr1d=np.array([1,2,3,4,5,6,7,8,9,10])
print("arrr =",arr1d)
print("arrr =",arr1d[2:8])
print("arrr =",arr1d[2:9:2])
print("arrr =",arr1d[-1])


arrr = [ 1  2  3  4  5  6  7  8  9 10]
arrr = [3 4 5 6 7 8]
arrr = [3 5 7 9]
arrr = 10


In [6]:
arr2d=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print("arr2d = ",arr2d)
print("arr2d = ",arr2d[1][1])
print("arr2d = ",arr2d[1])
print("arr2d = ",arr2d[:,1])

arr2d =  [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr2d =  5
arr2d =  [4 5 6]
arr2d =  [2 5 8]


### sorting

In [8]:
arr1=np.array([4,5,8,5,42,1,0])
print("arr1 = ",arr1)
print("arr1 = ",np.sort(arr1))
arr2=np.array([[1,23],
               [4,5],
               [0,3]])
print("arr2 = \n",np.sort(arr2,axis=0))
print("arr2 = \n",np.sort(arr2,axis=1))

arr1 =  [ 4  5  8  5 42  1  0]
arr1 =  [ 0  1  4  5  5  8 42]
arr2 = 
 [[ 0  3]
 [ 1  5]
 [ 4 23]]
arr2 = 
 [[ 1 23]
 [ 4  5]
 [ 0  3]]


### filtering

In [9]:
numbers=np.array([1,2,3,4,5,7,8,9,11,12])
print("Numbers = ",numbers[numbers%2==0])



Numbers =  [ 2  4  8 12]


### filtering with mask

In [11]:
mask=numbers>5
print("numbers greater than 5 = ",numbers[mask])

numbers greater than 5 =  [ 7  8  9 11 12]


### fancy indexing vs np.where


In [13]:
index=[0,2,5]
print("fancy indexing = ",numbers[index])

whereclause=np.where(numbers>7)
print("where clasue =",numbers[whereclause])


fancy indexing =  [1 3 7]
where clasue = [ 8  9 11 12]


In [14]:
conditionarr=np.where(numbers>5,numbers*2,numbers)
print("Condtional array =",conditionarr)

Condtional array = [ 1  2  3  4  5 14 16 18 22 24]


#### adding and removing data

In [16]:
arr1=np.array([1,2,3,4])
arr2=np.array([4,5,6,7])
arrconcati=np.concatenate((arr1,arr2))
print("concetinate array = ",arrconcati)

concetinate array =  [1 2 3 4 4 5 6 7]


### compatibility

In [18]:
print("compatibity = ",arr1.shape==arr2.shape)


compatibity =  True


In [22]:
original=np.array([[1,2,3],[5,6,7]])
new_row=np.array([9,10,12])

arr_new_row=np.vstack((original,new_row))
print("origianl = \n",original)
print("New_Row = \n",arr_new_row)


new_col=np.array([[4],[5]])
arr_new_col=np.hstack((original,new_col))

print("origianl = \n",original)
print("New_col = \n",arr_new_col)



origianl = 
 [[1 2 3]
 [5 6 7]]
New_Row = 
 [[ 1  2  3]
 [ 5  6  7]
 [ 9 10 12]]
origianl = 
 [[1 2 3]
 [5 6 7]]
New_col = 
 [[1 2 3 4]
 [5 6 7 5]]


In [24]:
arra=np.array([1,2,4,5,6,4,5,8,20,1])
delw=np.delete(arra,8)
print("Delted array = ",delw)

Delted array =  [1 2 4 5 6 4 5 8 1]
